#!/usr/bin/env bash
# ----------------------------------------------
# Robust relative-pose RANSAC iteration benchmark
# ----------------------------------------------
# Runs each solver (5pt, 8pt, upright 3pt, upright planar 3pt & 2pt)
# at a single EntoBench noise level (0.5 pix) with 25 % outliers (default).
# Generates log files capturing stdout for later parsing and statistics.
#
# Usage (from repo root):
#   ./scripts/run_robust_relpose.sh
#
# The script assumes the project has already been configured & built
# using the "build-relpose" build directory (generated by CMake).
# ----------------------------------------------
set -euo pipefail

# -------- parameters you might tweak ----------
NOISE_LEVEL=0.5           # pixel std-dev noise
NUM_PROBLEMS=1000         # number of synthetic problems per run
NUM_POINTS=64             # total correspondences per problem
# RANSAC iteration limits
MIN_ITERS=20
MAX_ITERS=1000
BUILD_DIR="build-relpose"
BIN_REL="src/ento-pose/rel-pose/bin/generate_robust_relative_pose_data"
OUT_DIR="logs/robust-relpose"
PRECISIONS=(float double) # comment out "double" if not needed
SOLVERS=(5pt 8pt upright_3pt upright_planar_3pt upright_planar_2pt)
# refinement type
REFINEMENT=nonlinear
# ----------------------------------------------

# Resolve binary path (relative to repo root)
BIN_PATH="${BUILD_DIR}/${BIN_REL}"
if [[ ! -x "${BIN_PATH}" ]]; then
  echo "Error: executable not found at ${BIN_PATH}" >&2
  echo "Have you run cmake && make in ${BUILD_DIR}?" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}"

echo "Running robust relative-pose benchmark …"

echo "Binary      : ${BIN_PATH}"
echo "Logs folder : ${OUT_DIR}"
echo "Noise        : ${NOISE_LEVEL} pix"
echo "Problems     : ${NUM_PROBLEMS}"
echo "RANSAC iters : ${MIN_ITERS}-${MAX_ITERS}"
echo "Refinement   : ${REFINEMENT}"

run_one() {
  local solver=$1
  local precision=$2
  local logfile="${OUT_DIR}/${solver}_${precision}.log"

  echo -e "\n>>> ${solver}  (${precision})  …" | tee -a "${logfile}"
  "${BIN_PATH}" \
    --solver-type "${solver}" \
    --noise "${NOISE_LEVEL}" \
    --problems "${NUM_PROBLEMS}" \
    --points "${NUM_POINTS}" \
    --precision "${precision}" \
    --refinement "${REFINEMENT}" \
    --min-iterations "${MIN_ITERS}" \
    --max-iterations "${MAX_ITERS}" \
    | tee -a "${logfile}"
}

for prec in "${PRECISIONS[@]}"; do
  for solver in "${SOLVERS[@]}"; do
    run_one "${solver}" "${prec}"
  done
done

echo -e "\nAll runs finished. Logs saved to ${OUT_DIR}" 